user-service:
  build: ./active-directory
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  ports:
    - "3000:3000"

message-service-web:
  build: ./message-service
  command: python -u app.py
  ports:
    - "4000:4000"
  links:
    - message-service-db:db
message-service-db:
  image: mongo:3.0.2
  ports:
    - "27017:27017"

gateway-service:
  build: ./gateway-service
  command: python app.py
  ports:
    - "2000:2000"
